# Generated by Django 3.1.5 on 2021-02-11 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='extendedUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('isTeacher', models.BooleanField(default=False)),
                ('isStudent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Gallary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('flink', models.CharField(max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('name', models.CharField(default='', max_length=255)),
                ('sem', models.IntegerField()),
                ('dob', models.DateField()),
                ('phnumber', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('flink', models.CharField(max_length=20000)),
                ('year', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('name', models.CharField(default='', max_length=255)),
                ('phnumber', models.CharField(max_length=10)),
                ('qualification', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='To',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=2000)),
                ('ylink', models.CharField(max_length=2000)),
                ('subject_name', models.CharField(max_length=2000)),
                ('module', models.CharField(max_length=100)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webmain.subject')),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='Teacher_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webmain.teacher'),
        ),
        migrations.CreateModel(
            name='Referance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=2000)),
                ('flink', models.CharField(max_length=4000)),
                ('module', models.CharField(max_length=100)),
                ('subject_name', models.CharField(max_length=2000)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webmain.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Internal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('flink', models.CharField(max_length=4000)),
                ('subject_name', models.CharField(max_length=1000)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webmain.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('flink', models.CharField(max_length=4000)),
                ('subject_name', models.CharField(max_length=1000)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webmain.subject')),
            ],
        ),
    ]
