# Generated by Django 3.1.5 on 2021-02-11 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webmain', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='To',
        ),
    ]
