# Generated by Django 3.1.5 on 2021-02-11 02:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmain', '0002_delete_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 2, 11, 8, 25, 45, 739788)),
        ),
    ]
