# Generated by Django 3.1.4 on 2021-01-10 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webmain', '0002_auto_20210110_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='tid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webmain.myappuser'),
        ),
    ]
