# Generated by Django 3.1.4 on 2021-01-10 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmain', '0003_auto_20210110_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myappuser',
            name='phone',
        ),
        migrations.AddField(
            model_name='myappuser',
            name='isTeacher',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
