# Generated by Django 3.1.5 on 2021-02-22 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmain', '0003_syllabus_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 2, 22, 20, 22, 47, 386854)),
        ),
    ]
