# Generated by Django 3.1.7 on 2021-03-26 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmain', '0004_auto_20210222_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 3, 26, 15, 34, 33, 984154)),
        ),
    ]
