# Generated by Django 3.1.4 on 2021-01-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmain', '0005_auto_20210110_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='subjects',
            new_name='phnumber',
        ),
        migrations.AddField(
            model_name='teacher',
            name='qualification',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
