# Generated by Django 3.1.4 on 2021-01-10 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmain', '0007_auto_20210110_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='phnumber',
            field=models.CharField(max_length=12),
        ),
    ]
