# Generated by Django 3.1.4 on 2021-01-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmain', '0010_attendance_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='teacher',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
