# Generated by Django 3.1.4 on 2021-01-12 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webmain', '0011_auto_20210112_1230'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
