# Generated by Django 3.1.4 on 2021-01-12 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webmain', '0012_delete_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
    ]
