# Generated by Django 3.1.4 on 2021-01-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmain', '0013_remove_student_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phnumber',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phnumber',
            field=models.CharField(max_length=10),
        ),
    ]
