# Generated by Django 3.1.4 on 2021-01-12 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webmain', '0014_auto_20210112_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='sid',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='tid',
            new_name='user',
        ),
    ]
