# Generated by Django 3.1.4 on 2021-01-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmain', '0015_auto_20210112_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='isTeachear',
            field=models.BooleanField(default=False),
        ),
    ]
