# Generated by Django 3.1.4 on 2021-01-13 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('webmain', '0016_teacher_isteachear'),
    ]

    operations = [
        migrations.CreateModel(
            name='extendedUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('isTeacher', models.BooleanField(default=False)),
                ('isStudent', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='isTeachear',
        ),
    ]
