# Generated by Django 3.1.4 on 2021-01-15 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webmain', '0017_auto_20210113_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='tid',
        ),
        migrations.AddField(
            model_name='subject',
            name='Teacher_name',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='webmain.teacher'),
            preserve_default=False,
        ),
    ]
