# Generated by Django 3.1.4 on 2021-01-15 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webmain', '0018_auto_20210115_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webmain.subject'),
        ),
    ]
